### ISSUE TITLE
Any hope for a Raspbian port?

### ISSUE THREAD

**Issue by dcjkfgdjhd** [veldenb/plugin.program.moonlight-qt#13]
Hello!

This plugin looks really great, and a quick test on LibreELEC looked very promising.

However, for various compatibility reasons, I need to stick with Raspbian OS Lite on my RasPi.

Is there any hope that this plugin could be ported to that platform? I guess it should mainly be required to disable functions, as Moonlight-QT runs on Raspbian without any of the Docker magic. One challenge would be that the latest official KODI version for Raspbian is still 18.7, which, if I understand correctly, still uses Python 2.

I tried doing it myself, but I am afraid there are too many things about this plugin that I don't fully understand...

Thank you very much, and cheers!

**Comment by veldenb** [comment]
Hi,

I think I would encounter several incompatibilities between LibreELEC and Raspbian which would require rewriting several parts of the plugin. Python 2/3 is also a problem because Kodi on python 3 differs a lot from previous versions and would require a separate new plugin. I may try to do that some day but currently I do not have the time to do so.
