### ISSUE TITLE
Feature Request: Support custom provided moonlight

### ISSUE THREAD

**Issue by ChrisOboe** [veldenb/plugin.program.moonlight-qt#21]
I really would like to have a nice moonlight launcher in kodi, but i would prefer that this plugin could just launch a existing moonlight-qt installation without all the magic to install a version (since i have installed moonlight through my distros package manager anyways). 

ideally there would be a flag if moonlight is distributed by this script, or if just a existing moonlight is assumed and used.

**Comment by veldenb** [comment]
Hi,

I think with some adjustments that should be possible.

**Comment by Slugsh** [comment]
I've been looking for a great moonlight-qt launcher aswell, this one seems to do the trick! I'm using Raspberry PI OS, and I can install moonlight-qt from provided repo, so opton to choose already installed moonlight-qt would be great.

**Comment by Philly-V** [comment]
This would be great.  I use a lightweight RPi OS buster, and moonlight needs a workaround regarding compatible graphics drivers to work. It would be great if it was possible to use the installed and working moonlight.

**Comment by veldenb** [comment]
I'm currently on holidays, but I think the easiest way is to check if the moonlight executable exists in the standard local bin paths. Another option would be to add a configuration item to define a path to the moonlight executable.

**Comment by veldenb** [comment]
This is an early version that should work on Raspbian. I tested it on Bullseye but I would expect it to work on Buster too.
The plugin uses apt to install moonlight if it isn't installed yet and launches moonlight from ` /usr/bin/moonlight-qt` .

I would recommend to start Kodi from a text-console and uninstall the old plugin including the configuration before installing this one. You will need to pair your game PC again because the moonlight-configuration is stored in Kodi's userdata and not in moonlight default config path for practical reasons.

I've only tested the plugin from a console. Not from X or Wayland, that might work and it may not.

Forcing a EGL resolution doesn't seem to work yet on Raspbian, need to look into that. Using the same audio device in moonlight as configured in Kodi should work.

Let me know what works and what doesn't :)


[plugin.program.moonlight-qt-main.zip](https://github.com/veldenb/plugin.program.moonlight-qt/files/9561218/plugin.program.moonlight-qt-main.zip)
