### ISSUE TITLE
crash when using kms driver libreelec 10.3 rpi4

### ISSUE THREAD

**Issue by sm4rty-github** [veldenb/plugin.program.moonlight-qt#28]
when running LE 10.3 on RPi 4 the whole system system crashs when I start a stream.

then gui works fine, but when start a stream the rpi goes blackscreen and dies.

when running running with fkms driver the stream works but without audio and no hdmi-cec

where can i find the right log?

**Comment by veldenb** [comment]
I found LibreELEC 10.3 also quite unstable on my own Pi4. Some things changed from 10.1 to 10.2 that is causing instabilities, but I thought it was mainly because I connect my receiver to the secondary HDMI-port of the Pi and the driver got confused.
So I rolled back to LibreELEC 10.1, on that version everything is running stable for me. How is your experience on LibreELEC 10.1?

**Comment by sm4rty-github** [comment]
i switched directly from LE 9 to LE 10.3 per updater.
I never used LE 10.1 but maybe I will give it a try tomorrow

**Comment by sm4rty-github** [comment]
My Raspberry isnt booting with LE 10.0.1
it only shows a blackscreen and is dead.

**Comment by veldenb** [comment]
Strange, sounds like a badly written image on the SD-card

**Comment by veldenb** [comment]
Closing stale issue
