### ISSUE TITLE
UI scaling issues

### ISSUE THREAD

**Issue by jorys-paulin** [veldenb/plugin.program.moonlight-qt#53]
Hello!

The Moonlight UI seems to be scaled weirdly, as if it's running at 4K (on a 1080p monitor) and at 50% scale, so everything looks tiny, especially the icons of the top bar.

I've tried to use the new "EGL resolution" option, but that didn't change anything. I haven't been able to launch Moonlight from a terminal to see if it's related to the plugin or Moonlight itself.

I'm running LibreELEC `11.0.4` (downloaded from the Raspberry Pi imager), which is apparently running Kodi `20.2.0`. I'm running version `0.4.3` of the plugin.

![Moonlight Kodi_2024-01-13_13-52-27](https://github.com/veldenb/plugin.program.moonlight-qt/assets/5084309/eac2cf99-7de2-4f43-b583-08fc29730552)
![Moonlight Kodi_2024-01-13_13-52-52](https://github.com/veldenb/plugin.program.moonlight-qt/assets/5084309/cabd592d-7a1d-406a-b9db-74a9bf15a30e)
![Moonlight Kodi_2024-01-13_13-52-41](https://github.com/veldenb/plugin.program.moonlight-qt/assets/5084309/2d920721-868c-4d5a-847d-95018946bb8a)

**Comment by veldenb** [comment]
Hi, scaling the UI is a bit of a balancing act. Because the Pi has no window manager we have to hint scaling values using three environment variables:
```
QT_SCALE_FACTOR
QT_QPA_EGLFS_PHYSICAL_WIDTH
QT_QPA_EGLFS_PHYSICAL_HEIGHT
```
For the long version see https://github.com/veldenb/plugin.program.moonlight-qt/issues/11.

Scaling the UI too small and stuff becomes unreadable, scaling the UI to big leads to a cut-off configuration page or UI artifacts.

Since last time I changed the scaling factor it looks like the configuration page got somewhat denser, so I could scale the UI somewhat larger: https://github.com/veldenb/plugin.program.moonlight-qt/commit/09d464d7f4f7ada31547f5df2a3fa61ab8e3c0c6.

Can you try installing the [latest version](https://github.com/veldenb/plugin.program.moonlight-qt/archive/refs/heads/main.zip) to check if the UI looks somewhat better? Feel free to try fiddling with the variables yourself, the current values are the best I could find.

**Comment by jorys-paulin** [comment]
Hello! Thanks for your response.

Here's how the build looks like on my 1080p screen, the scaling looks correct now:
![09d464d - Moonlight Kodi_2024-01-16_11-23-59](https://github.com/veldenb/plugin.program.moonlight-qt/assets/5084309/c3186c93-4429-4a00-8e97-0b62c76ff88e)
![09d464d - Moonlight Kodi_2024-01-16_11-23-29](https://github.com/veldenb/plugin.program.moonlight-qt/assets/5084309/76763d1c-2288-417c-a3c0-b98ed9b8893b)

I wasn't able to test at 4K or 720p however, maybe the scaling is broken there now.

**Comment by veldenb** [comment]
I checked those and they look the same on my TV as your screenshot. The new scaling will be included in the next release :)
